---

- name: install {{ webserver }}
  yum:
    name: "{{ webserver }}"
    state: latest

- name: enable {{ webserver }} at boot
  service:
    name: "{{ webserver }}"
    enabled: yes

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644

- name: restart tomcat
  service:
    name: "{{ webserver }}"
    state: restarted
